### ISSUE TITLE
Avatar border color API

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#22]

**Comment by web-padawan** [comment]
By @jouni from the discussion in Slack:

> there’s now a white (lumo base color) border around all avatars when they are in a group. That’s unwanted. 

> The border should only be used when a “user color” has been defined. 

> Also, notice the ugly aliasing artifacts around the img avatar, between the border. Could be avoided with different CSS

**Comment by web-padawan** [comment]
Now when #26 is merged, we should support user border and focus outline at the same time:

![border](https://user-images.githubusercontent.com/10589913/86592742-af980380-bf9c-11ea-9f23-08830b363684.png)

Suggested styles (attribute & custom CSS property names to be discussed):

```css
:host([has-active-user]) {
  position: relative;
}

:host([has-active-user])::before {
  position: absolute;
  z-index: 1;
  content: '';
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  border-radius: 50%;
  box-shadow: inset 0 0 0 2px var(--_active-user-color);
}
```
