### ISSUE TITLE
Avatars with incorrect color index are white

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-avatar#69]
The background-color CSS rule does not have a fallback value:

https://github.com/vaadin/vaadin-avatar/blob/f213021d1485e71084b39132dad8e6c6af95a685/src/vaadin-avatar.html#L53-L56

If `colorIndex` is set to a value which does not have corresponding color, the avatar becomes white.

We might fix that in Lumo by overriding like this:
```css
 :host([has-color-index]) { 
   background-color: var(--vaadin-avatar-user-color, var(--lumo-contrast-10pct)); 
 } 
```
